#!/bin/sh
set -euf
source "$(dirname "$0")/config"

task='./scripts/check'
if [ "$#" -eq 1 ]; then
  task=$1
fi

while :; do
  output="$($task 2>&1 || :)"
  clear
  echo '===================='
  echo "$output"
  sleep 1
done
