#!/bin/bash
set -e
source "$(dirname "$0")/config"

WATCH_COMMAND="
  lines=\$((\$(tput lines)-1))
  cargo check        \
    $CARGO_ARGS      \
    --color always   \
    2>&1 |           \
      head -n\$lines
"

watchexec          \
  --clear          \
  --watch src      \
  --exts rs        \
  "$WATCH_COMMAND"
