#!/bin/bash
set -e
source "$(dirname "$0")/config"

watchexec          \
  --restart        \
  --watch src      \
  --exts rs        \
  "
    clear
    cargo check            \
      $CARGO_ARGS          \
      --quiet              \
      --color always       \
    2>&1 | less -R -X
  "
